version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - npm install
  build:
    commands:
      # - yarn build
  post_build:
    commands:
      - npm run semantic-release
cache:
  paths:
    - node_modules
